import Head from 'next/head'
import Image from 'next/image'
import Center from '../Components/Center'
import { LeftSidebar } from '../Components/LeftSidebar'
import RightSidebar from '../Components/RightSidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-[#f3f2ef] flex px-14'>
        <LeftSidebar/>
        <Center/>
        <RightSidebar/>
      </main>
    </div>
  )
}
